version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: grapesjs
    versions:
    - 0.16.34
    - 0.16.41
    - 0.16.44
    - 0.16.45
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.3.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 6.0.3
    - 7.0.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.0
  - dependency-name: redux
    versions:
    - 4.0.5
